check whether tl0 user is a spam user using content of user's bio
discourse/discourse-akismet-fork pull request #19
Opened 2019-01-28 15:49 UTC by mrfinch

https://meta.discourse.org/t/detect-spam-tl0-users-when-using-akismet-plugin/107731

2019-01-30 09:16 UTC, mrfinch commented
bump :bowing_man:

2019-02-01 04:53 UTC, SamSaffron commented
I would like to completely hold off here on this until @eviltrout  is done with the review queue

2019-02-01 04:55 UTC, coding-horror commented
We have super mega giga blocked this person now, which is a problem..

On Thu, Jan 31, 2019 at 8:53 PM Sam <notifications@github.com> wrote:

> I would like to completely hold off here on this until @eviltrout
> <https://github.com/eviltrout> is done with the review queue
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/discourse/discourse-akismet/pull/19#issuecomment-459605775>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABc7VW509zE-RrWKpURTnwiJOuH_kZjPks5vI8g7gaJpZM4aWMtW>
> .
>

2019-02-01 08:25 UTC, mrfinch commented
It is just a backend task which we can integrate to review queue later. Maybe we can push the change behind a flag for now, what do you think?

2019-02-01 08:41 UTC, mrfinch commented
sorry i thought you commented in my other PR, updated my comment above :bowing_man:

2019-02-05 14:18 UTC, eviltrout commented
I thought I replied already to this but I guess I didn't?

The review queue hasn't touched Akismet so it is not blocking this at this point. I would prefer people not wait for my work for this kind of change @SamSaffron

2019-02-05 14:34 UTC, ZogStriP commented on jobs/check_akismet_user.rb
> +      user = User.where(id: args[:user_id]).first
`find_by` is more consistent.

```suggestion
      user = User.find_by(id: args[:user_id])
```

2019-02-05 14:35 UTC, ZogStriP commented on jobs/check_akismet_user.rb
> +      return if user.blank?
I think you meant `nil`?

```suggestion
      return if user.nil?
```

2019-02-05 14:35 UTC, ZogStriP commented on lib/discourse_akismet/user.rb
> +	class User
Indentation is off here.

2019-02-05 15:16 UTC, ZogStriP commented on jobs/check_for_spam_users.rb
> +    every 10.minutes
That seems a bit excessive

2019-02-06 00:50 UTC, mrfinch commented on jobs/check_for_spam_users.rb
> +    every 10.minutes
I can actually increase this time if that is the case. This job will pick up the users only on the first run. On subsequent runs, all users will already be processed courtesy of events here: https://github.com/discourse/discourse/pull/6958

Also, I'm just checking for TL0 users so we are not going to process all users even on the first run.

What do you think should be an ideal time here?

cc @coding-horror

2019-02-08 08:40 UTC, mrfinch commented on jobs/check_for_spam_users.rb
> +    every 10.minutes
@ZogStriP ping :bowing_man:

2019-02-08 09:03 UTC, ZogStriP commented on jobs/check_for_spam_users.rb
> +    every 10.minutes
> Also, I'm just checking for TL0 users so we are not going to process all users even on the first run.

Yeah, that makes it less intensive. It's fine then.

2019-02-11 13:32 UTC, ZogStriP commented on lib/discourse_akismet/user.rb
> +      ::User.where(trust_level: 0).where.not(id: UserCustomField.where(name: DiscourseAkismet::AKISMET_STATE_KEY).pluck(:user_id))
Using `pluck` here is going to use lots of RAM unecessary pulling all the user ids in the application server instead of using a subquery.

```suggestion
      ::User.where(trust_level: 0).where.not(id: UserCustomField.where(name: DiscourseAkismet::AKISMET_STATE_KEY).select(:user_id))
```

2019-02-11 13:34 UTC, ZogStriP commented on plugin.rb
> +    Jobs.enqueue(:check_akismet_user, user_id: user_profile.user_id)
We might want to ensure there isn't another `check_akismet_user` job already scheduled for that user

2019-02-11 13:35 UTC, ZogStriP commented on spec/discourse_akismet/user_spec.rb
> +  random_bio = 'random profile'
Variable outside test methods should be declared using this syntax

```suggestion
  let(:random_bio) { 'random profile' }
```

2019-02-11 13:36 UTC, ZogStriP commented on spec/discourse_akismet/user_spec.rb
> +  before do
This `before` block should be merged with the previous block

2019-02-11 13:37 UTC, ZogStriP commented on spec/discourse_akismet/user_spec.rb
> +  describe '#profile_content' do
I don't feel this test is necessary as we're already testing the result of the `profile_content` method in other tests

2019-02-11 13:38 UTC, ZogStriP commented on spec/discourse_akismet/user_spec.rb
> +    # one on create and one on profile update in before block
No, we only want one job to be ever enqueued at a time.

2019-02-11 13:40 UTC, ZogStriP commented on lib/discourse_akismet/user.rb
> +      @user.upsert_custom_fields(to_update)
There's no point in having the `to_update` variable

```suggestion
      @user.upsert_custom_fields(DiscourseAkismet::AKISMET_STATE_KEY => state)
```

2019-02-11 13:42 UTC, ZogStriP commented on spec/discourse_akismet/user_spec.rb
> +      user.upsert_custom_fields({DiscourseAkismet::AKISMET_STATE_KEY => DiscourseAkismet::NEEDS_REVIEW})
In Ruby, you don't need the `{` and `}` when passing a hash to a method

```suggestion
      user.upsert_custom_fields(DiscourseAkismet::AKISMET_STATE_KEY => DiscourseAkismet::NEEDS_REVIEW)
```

2019-02-11 13:42 UTC, ZogStriP commented on spec/jobs/check_akismet_user_spec.rb
> +  	SiteSetting.akismet_api_key = 'not_a_real_key'
Indentation is wrong here.

2019-02-11 13:43 UTC, ZogStriP commented on spec/jobs/check_akismet_user_spec.rb
> +  	Excon.expects(:post).returns(mock_response.new(200, 'true'))
Indentation is wrong here

2019-02-13 03:27 UTC, mrfinch commented
All requested changes are done. It can be reviewed now.

2019-02-15 03:40 UTC, mrfinch commented
bump :bowing_man:

2019-02-19 00:18 UTC, coding-horror commented
can you take a look @ZogStriP

2019-02-19 16:25 UTC, ZogStriP commented on jobs/check_akismet_user.rb
> +      user = User.find_by(id: args[:user_id])
```suggestion
      return unless user = User.find_by(id: args[:user_id])
```

2019-02-19 16:30 UTC, ZogStriP commented on lib/discourse_akismet/user.rb
> +      Jobs::CheckAkismetUser.jobs.select do |job|
This method should probably be extracted and put in `app/jobs/base.rb` alongside `def self.scheduled_for`

2019-02-19 17:02 UTC, ZogStriP commented on lib/discourse_akismet/user.rb
> +  class User
This is confusing as this is not really a user. I think we need a better name. Something like `CheckSpamUser` or `UserChecker`.

2019-02-19 17:03 UTC, ZogStriP requested changes
Need to rename the `DiscourseAkismet::User` class.

2019-02-20 06:40 UTC, mrfinch commented on lib/discourse_akismet/user.rb
> +      Jobs::CheckAkismetUser.jobs.select do |job|
I have made the change and created PR for same: https://github.com/discourse/discourse/pull/7033

2019-02-20 06:41 UTC, mrfinch commented
@ZogStriP I have made the changes and opened one more PR related to changes u asked for here: https://github.com/discourse/discourse/pull/7033

2019-02-20 13:24 UTC, tgxworld commented on plugin.rb
> +    Jobs.enqueue(:check_akismet_user, user_id: user_profile.user_id) unless Jobs.has_same_job_been_enqueued?('check_akismet_user', user_id: user_profile.user_id)
I'm not comfortable with this code here since it forces us to support [code](https://github.com/discourse/discourse/pull/7033) in core for a single plugin. Is there a reason to even enqueue this job if `DiscourseAkismet::CheckSpamUser#should_check_for_spam?` is going to always return false once the user has been checked.

2019-02-20 13:58 UTC, mrfinch commented on plugin.rb
> +    Jobs.enqueue(:check_akismet_user, user_id: user_profile.user_id) unless Jobs.has_same_job_been_enqueued?('check_akismet_user', user_id: user_profile.user_id)
- I don't think that code is useful for just this plugin, it can be used by anyone else too who has to do a similar check. That code doesn't depend on this plugin. Though if we are going to remove the check itself, I can remove that code.
- I actually realized it's a bug, we shouldn't be returning false always for `check_for_spam?` once the user has been checked since spam user can update his profile later with spam content, I will be removing that check.
- I think I can pass the changes which happen to model here or trigger a different event when profile_content is updated. If the profile_content has been updated then we can proceed to check for spam user.

2019-02-20 14:17 UTC, tgxworld commented on plugin.rb
> +    Jobs.enqueue(:check_akismet_user, user_id: user_profile.user_id) unless Jobs.has_same_job_been_enqueued?('check_akismet_user', user_id: user_profile.user_id)
> * I don't think that code is useful for just this plugin, it can be used by anyone else too who has to do a similar check. That code doesn't depend on this plugin. Though if we are going to remove the check itself, I can remove that code.

As of now, only the plugin requires that piece of code so I don't see a need for it to be extracted into core. Also the method is dangerous because a particular job can have thousands of jobs en-queued. When that happens, the piece of code is going to load everything into memory in order to try and find a match.

Instead of always en-queuing a job, we should just run the `check_for_spam?` logic before en-queuing the job. The job should just pass the user and the `bio_raw` so that we have a way of differentiating the jobs without having to spend computation resources to ensure uniqueness of a job in the queue.

2019-02-20 15:08 UTC, mrfinch commented on plugin.rb
> +    Jobs.enqueue(:check_akismet_user, user_id: user_profile.user_id) unless Jobs.has_same_job_been_enqueued?('check_akismet_user', user_id: user_profile.user_id)
- I agree that the function to find whether the job is unique can be dangerous if not used properly. I will remove it since we have better alternatives.
- Akismet plugin currently user DiscourseEvent for the post so I think it will be better to use them. I will change ```DiscourseEvent.trigger(:user_profile_updated, self)``` to trigger only if bio_raw is changed. Also, I will change the name of the event to `user_profile_content_updated`. I don't expect the number of bio updates to be very huge anyway. I will pass the `user` and `bio_raw` to the event too to avoid DB calls.
- Also, I think it will be better if we just enqueue the job and let it do the checking whether to process user or not by checking whether SiteSetting is enabled etc since it will be very fast anyway. Also, I think it will be better to check it later when the worker picks it up from queue instead of blocking the thread which checks whether to enqueue or not. This will be a better design too for in case we need to add any computation heavy checks in future.  

What do you think?

2019-02-21 01:05 UTC, tgxworld commented on plugin.rb
> +    Jobs.enqueue(:check_akismet_user, user_id: user_profile.user_id) unless Jobs.has_same_job_been_enqueued?('check_akismet_user', user_id: user_profile.user_id)
> * Akismet plugin currently user DiscourseEvent for the post so I think it will be better to use them. I will change `DiscourseEvent.trigger(:user_profile_updated, self)` to trigger only if bio_raw is changed. Also, I will change the name of the event to `user_profile_content_updated`. I don't expect the number of bio updates to be very huge anyway. I will pass the `user` and `bio_raw` to the event too to avoid DB calls.

I think you can use a `DiscourseEvent` which always en-queue on `user_profile_created`. For `user_profile_updated`, you can use the `user` object to check if the `bio_raw` is actually changed before en-queuing the job.

> * Also, I think it will be better if we just enqueue the job and let it do the checking whether to process user or not by checking whether SiteSetting is enabled etc since it will be very fast anyway. Also, I think it will be better to check it later when the worker picks it up from queue instead of blocking the thread which checks whether to enqueue or not. 

Since the checks are fast, it is better to not have a job be en-queued since it adds overhead to the Sidekiq queue.

> This will be a better design too for in case we need to add any computation heavy checks in future.

When there are heavy computation checks in the future, we can easily move the checks into Sidekiq. Since the checks are simple for now, I think we should keep the checks out of the Sidekiq queue. Also note that job en-queued are not executed immediately. If the checks are in the job itself, the conditions of whether we check for spam or not can change before the job executes.

2019-02-21 07:14 UTC, mrfinch commented on plugin.rb
> +    Jobs.enqueue(:check_akismet_user, user_id: user_profile.user_id) unless Jobs.has_same_job_been_enqueued?('check_akismet_user', user_id: user_profile.user_id)
I have made changes, have a look @tgxworld

2019-02-28 02:46 UTC, mrfinch commented
@tgxworld @ZogStriP ping :bowing_man:

2019-03-04 16:15 UTC, mrfinch commented
@tgxworld @ZogStriP bump :bowing_man:

2019-03-10 15:04 UTC, tgxworld commented on plugin.rb
> +      Jobs.enqueue(:check_akismet_user, user_id: self.user_id, profile_content: self.bio_raw) if DiscourseAkismet::CheckSpamUser.new(self.user, self.bio_raw).should_check_for_spam?
The code here and the code on line 69 is being duplicated. I think it'll be better to refactor it into a private method.

2019-03-10 15:05 UTC, tgxworld commented on jobs/check_for_spam_users.rb
> +    every 10.minutes
Do we need this run this every 10 minutes? Will running this in a onceoff job be sufficient?

2019-03-10 15:06 UTC, tgxworld commented on lib/discourse_akismet/check_spam_user.rb
> +        extra_args[:comment_author_email] = @user.try(:email)
```suggestion
        extra_args[:comment_author_email] = @user&.email
```

2019-03-10 15:09 UTC, tgxworld commented on lib/discourse_akismet/check_spam_user.rb
> +      ::User.where(trust_level: 0).where.not(id: UserCustomField.where(name: DiscourseAkismet::AKISMET_STATE_KEY).select(:user_id))
This SQL statement can be quite dangerous on large sites. If  `UserCustomField.where(name: DiscourseAkismet::AKISMET_STATE_KEY).select(:user_id)` returns a large collection, `where.not` is going to result in a query that is slow since the Postgres planner will not be able to utilize the index. What you can do here instead is to do a join on `UserCustomField` and then filter the records accordingly.

2019-03-11 01:36 UTC, tgxworld commented on jobs/check_akismet_user.rb
> +      return if args[:user_id].blank? || args[:profile_content].blank?
Usually we want to raise a `Discourse::InvalidParameter` error instead of silently returning from the job.

2019-03-11 01:37 UTC, tgxworld commented on jobs/check_for_spam_users.rb
> +      return if SiteSetting.akismet_api_key.blank?
Can akismet be enabled if the akismet_api_key is blank? This check here seems unnecessary to me.

2019-03-11 01:37 UTC, tgxworld commented on jobs/check_for_spam_users.rb
> +      DiscourseAkismet::CheckSpamUser.to_check.each do |user|
```suggestion
      DiscourseAkismet::CheckSpamUser.to_check.find_each do |user|
```
If there are alot of users to check, especially on the first run, we don't want to be loading all the users into memory at once.

2019-03-11 01:38 UTC, tgxworld commented on lib/discourse_akismet.rb
> +    MessageBus.publish('/akismet_counts', msg, user_ids: ::User.staff.pluck(:id))
Why is `::User` necessary here?

2019-03-11 01:39 UTC, tgxworld commented on lib/discourse_akismet/check_spam_user.rb
> +          # should we notify admin user for it?
Has this comment been resolved? Generally, we don't want to leave comments that are pending a TODO in the code base.

2019-03-11 01:40 UTC, tgxworld commented on lib/discourse_akismet.rb
> +  AKISMET_STATE_KEY = 'AKISMET_STATE'
The constants above should probably be declared in `DiscourseAkisment::CheckSpamUser` instead.

2019-03-11 01:41 UTC, tgxworld commented on lib/discourse_akismet/check_spam_user.rb
> +          move_to_state(DiscourseAkismet::CHECKED)
```suggestion
move_to_state(client.comment_check(args) ? DiscourseAkismet::NEEDS_REVIEW : DiscourseAkismet::CHECKED)`

2019-03-11 01:43 UTC, tgxworld commented on lib/discourse_akismet/check_spam_user.rb
> +      return false if @user.blank? || !SiteSetting.akismet_enabled? || SiteSetting.akismet_api_key.blank?
Same as https://github.com/discourse/discourse-akismet/pull/19/files#r264072245

2019-03-11 01:47 UTC, tgxworld commented on lib/discourse_akismet/check_spam_user.rb
> +      return false if @user.trust_level != TrustLevel[0]
Do we still need this if we're always only passing users that are always trust level 0.

2019-03-11 01:53 UTC, tgxworld commented on lib/discourse_akismet/check_spam_user.rb
> +      return unless should_check_for_spam?
Are we calling this method from anywhere else? Otherwise, I think this should be a private method and we don't need this conditional.

2019-03-11 01:56 UTC, tgxworld commented on spec/discourse_akismet/check_spam_user_spec.rb
> +  let(:random_bio) { 'random profile' }
```suggestion
  let(:bio) { 'random profile' }
```
I would just name it `:bio` since there is nothing random about the bio.

2019-03-11 01:59 UTC, tgxworld commented on spec/discourse_akismet/check_spam_user_spec.rb
> +    user_profile.save
```suggestion
    user.user_profile.bio_raw.update!(bio_raw: bio)
```

2019-03-11 01:59 UTC, tgxworld commented on lib/discourse_akismet/check_spam_user.rb
> +    def args
Does this method  need to be public?

2019-03-11 02:00 UTC, tgxworld commented on lib/discourse_akismet/check_spam_user.rb
> +    def should_check_for_spam?
Does this method need to be public?

2019-03-11 02:02 UTC, tgxworld commented on spec/discourse_akismet/check_spam_user_spec.rb
> +    end
```suggestion
job_args = Jobs::CheckAkismetUser.jobs.first.args
expect(job_args["user_id"]).to eq(user.id)
```

2019-03-11 02:03 UTC, tgxworld commented on spec/discourse_akismet/check_spam_user_spec.rb
> +  describe '#args' do
No need to test this if the method is meant to be private

2019-03-11 02:03 UTC, tgxworld commented on spec/discourse_akismet/check_spam_user_spec.rb
> +  describe '#move_to_state' do
No need to test this if the method is meant to be private.

2019-03-11 02:05 UTC, tgxworld commented on spec/jobs/check_akismet_user_spec.rb
> +    Excon.expects(:post).returns(mock_response.new(200, 'true'))
Can you have a look at using `webmock` here instead? Thank you!

2019-03-11 12:54 UTC, mrfinch commented on jobs/check_for_spam_users.rb
> +    every 10.minutes
No, there might be cases where someone installs/uninstalls so we will need to run it again. Also, this runs for only TL0 users so it won't be a performance issue even. I had a discussion above in this PR with @ZogStriP about it.

2019-03-11 12:57 UTC, mrfinch commented on jobs/check_for_spam_users.rb
> +      return if SiteSetting.akismet_api_key.blank?
We do this check already for the post. Maybe @eviltrout can help here

2019-03-11 12:58 UTC, tgxworld commented on jobs/check_for_spam_users.rb
> +    every 10.minutes
> there might be cases where someone installs/uninstalls

This is so rare though that I don't see carrying a scheduled job that will be doing nothing most of the time to be useful. If need be, we can just provide someone with a button in the admin interface to trigger it.

2019-03-11 13:04 UTC, mrfinch commented on lib/discourse_akismet.rb
> +    MessageBus.publish('/akismet_counts', msg, user_ids: ::User.staff.pluck(:id))
previously CheckSpamUser was named User that's why. I have reverted this change.

2019-03-11 13:04 UTC, mrfinch commented on lib/discourse_akismet/check_spam_user.rb
> +          # should we notify admin user for it?
I'm removing this since we don't need it in this version

2019-03-11 13:06 UTC, mrfinch commented on lib/discourse_akismet.rb
> +  AKISMET_STATE_KEY = 'AKISMET_STATE'
Actually, these are going to be used in this file too. I plan to refactor it soon. String values are the same in both check_spam_user and this class.

2019-03-11 13:09 UTC, mrfinch commented on lib/discourse_akismet/check_spam_user.rb
> +      return false if @user.trust_level != TrustLevel[0]
I don't think we can trust everyone to pass user with trust_level 0 here. We need to do all checks before calling Akismet.

2019-03-11 13:14 UTC, mrfinch commented on lib/discourse_akismet/check_spam_user.rb
> +      return unless should_check_for_spam?
We call this before an enqueuing job.

2019-03-11 13:15 UTC, tgxworld commented on lib/discourse_akismet/check_spam_user.rb
> +      return unless should_check_for_spam?
Sorry I meant the method `move_to_state`

2019-03-11 13:16 UTC, tgxworld commented on lib/discourse_akismet/check_spam_user.rb
> +      return false if @user.trust_level != TrustLevel[0]
hmm I guess this is OK then since the check is cheap.

2019-03-11 13:17 UTC, mrfinch commented on spec/discourse_akismet/check_spam_user_spec.rb
> +    user_profile.save
fixed it, there was a typo in yr code. bio_raw is not needed in that line

2019-03-11 13:20 UTC, mrfinch commented on lib/discourse_akismet/check_spam_user.rb
> +    def should_check_for_spam?
yes, needs to be called before pushing the job to the queue

2019-03-11 13:22 UTC, mrfinch commented on spec/discourse_akismet/check_spam_user_spec.rb
> +  describe '#args' do
I think if there is a logic in a private method, it is better to have unit-tests corresponding to it.

2019-03-11 13:27 UTC, tgxworld commented on spec/discourse_akismet/check_spam_user_spec.rb
> +  describe '#args' do
This is a good video to watch about how much to test: https://www.youtube.com/watch?v=URSWYvyc42M

The method `args` to me should be a private method because it is only used by an instance of the class itself. If a method is private, we shouldn't be concerned about testing the method directly. Instead, you only want to test the public interfaces of the class which will also indirectly test the private methods that it calls.

2019-03-12 03:10 UTC, mrfinch commented on spec/discourse_akismet/check_spam_user_spec.rb
> +    end
Can you explain to me what does this suggestion help us in? You removed `end` here and not added it back. Am I missing anything?

2019-03-12 03:16 UTC, tgxworld commented on spec/discourse_akismet/check_spam_user_spec.rb
> +    end
Ignore the suggestion because Github's UI messed up what I was trying to propose. Basically, you don't need the complicated loop here since there is only going to be a single job enqueued. To get the job, you can just do 

```
job_args = Jobs::CheckAkismetUser.jobs.first.args
expect(job_args["user_id"]).to eq(1)
```

2019-03-12 03:57 UTC, mrfinch commented on lib/discourse_akismet/check_spam_user.rb
> +      ::User.where(trust_level: 0).where.not(id: UserCustomField.where(name: DiscourseAkismet::AKISMET_STATE_KEY).select(:user_id))
I tried this query: `User.joins(:user_custom_fields).where(trust_level: 0).where('user_custom_fields.name != ?', DiscourseAkismet::AKISMET_STATE_KEY)` but it fails in unit-tests because there are times when user has no custom field created so that user is not returned even though he is a TL0 user who needs to be reviewed. I think the user might not have any custom_field in production too, can you suggest me anyway where I can fix this case or suggest an alternate join query. 
Alternatively, we can first find TL0 users(which will be low) then use that list in UserCustomField to filter users thus using proper indexes, what do you think?

2019-03-12 04:40 UTC, mrfinch commented on spec/discourse_akismet/check_spam_user_spec.rb
> +    end
Actually, there can be multiple jobs enqueued since other tests will also put new jobs to queue so I will need to filter them out.

2019-03-18 03:12 UTC, mrfinch commented on jobs/check_for_spam_users.rb
> +    every 10.minutes
Can we add a job to queue on install? I'm thinking to add one job in `after_initialize` section of the plugin. After doing that, we can safely remove this job. The job which I will be pushing in `after_initialize` will just be pushed on server restart which will be relatively much less than this.

2019-03-18 03:13 UTC, mrfinch commented on spec/discourse_akismet/check_spam_user_spec.rb
> +  describe '#args' do
I saw the video and have made appropriate changes as you suggested. Thanks :bowing_man:

2019-03-18 03:13 UTC, mrfinch commented
@tgxworld have a look, most of the changes are done apart from the query optimization issue you raised

2019-03-18 12:46 UTC, mrfinch commented on lib/discourse_akismet/check_spam_user.rb
> +      ::User.where(trust_level: 0).where.not(id: UserCustomField.where(name: DiscourseAkismet::AKISMET_STATE_KEY).select(:user_id))
```
already_processed_user_ids = UserCustomField.where(user_id: User.where(trust_level: 0).select(:id), name: DiscourseAkismet::AKISMET_STATE_KEY).pluck(:user_id)
User.where(trust_level: 0).where.not(id: already_processed_user_ids)
```
How about this one?

2019-03-19 00:56 UTC, SamSaffron commented
@mrfinch I am afraid this is probably not going to be mergable anymore since we are migrating to reviewables. 

@romanrizzi  is going to follow up here and see how we introduce this feature in light of the new APIs.

2019-04-04 09:26 UTC, closed without merging