Review queue support
discourse/discourse-akismet-fork pull request #21
Opened 2019-03-14 18:36 UTC by romanrizzi

- `ReviewableAkismetPost` was added as an extension to the `Reviewable` API.
- Behaviour found in `AdminModQueueController` was ported to this class (+ new tests :metal:).
- Old controller was modified to support backwards compatibility.
- We check that new `Reviewable` API exists on boot.
- Some options in the logging were removed because they were being filtered.
- Provider custom template and style

![akismet-1](https://user-images.githubusercontent.com/5025816/54382494-e2fba400-466e-11e9-8665-9feedf5ed8ca.png)
![akismet-2](https://user-images.githubusercontent.com/5025816/54382504-e727c180-466e-11e9-92ca-b53263b8884f.png)

2019-03-14 19:21 UTC, eviltrout requested changes
Overall I think this is an excellent start. I've left a few small items inline, but there is one larger issue I think we need to sort out.

This implementation still uses custom fields to store the akismet state. If the Reviewable structures are present, they should already have the entire data model present to handle the states and transitions.

The PR needs to be adjusted so that if the Reviewable queue is present it does not do that.

Additionally, we will need a migration to migrate from the old custom fields to Reviewables, so the old history is still around.

2019-03-14 19:21 UTC, eviltrout commented on models/reviewable_akismet_post.rb
> +    build_action(actions, :dismiss, icon: 'times')
Thinking about it, this is an opportunity to standardize our terms. Rather than "Dismiss" I think we should use "Ignore" which is what the ReviewableFlaggedPost uses.

2019-03-14 19:21 UTC, eviltrout commented on app/controllers/discourse_akismet/admin_mod_queue_controller.rb
> +      deprecation_notice
If this is happening before every action it would be cleaner to use a `before` block.

2019-03-14 19:21 UTC, eviltrout commented on assets/javascripts/discourse/templates/components/reviewable-akismet-post.hbs
> +        <td class='user'>Akismet</td>
These lines are missing I18n.

2019-03-14 19:21 UTC, eviltrout commented on assets/stylesheets/reviewable_akismet_post_styles.scss
> +.reviewable-akismet-post {
I'm trying to standardize us on `kebab-case` for scss filenames and since this is a new file we might as well!

2019-03-14 19:21 UTC, eviltrout commented on lib/discourse_akismet.rb
> +            ReviewableAkismetPost.needs_review!(created_by: spam_reporter, target: post, topic: post.topic)
An akismet post should probably be `reviewable_by_moderator`

2019-03-14 19:21 UTC, eviltrout commented on models/reviewable_akismet_post.rb
> +    DiscourseAkismet.move_to_state(target, 'confirmed_spam')
If the `Reviewable` API is present, we shouldn't need to use the `move_to_state` methods. (I'll probably add a bigger comment about this to summarize.)

2019-03-14 19:21 UTC, eviltrout commented on spec/models/reviewable_akismet_post_spec.rb
> +      expected_action_id = :confirm_spam
Very minor but if you're only using the variable in one place, why not inline the `:confirm_spam` value in your expect?

2019-03-14 19:55 UTC, romanrizzi commented on spec/models/reviewable_akismet_post_spec.rb
> +      expected_action_id = :confirm_spam
It's just my coding style. I think that makes the test more readable. Will inline because it's pretty clear in these tests.

2019-03-15 20:24 UTC, eviltrout approved these changes
This looks good now! Let's merge on Monday since the weekend is :ghost:

2019-03-18 14:42 UTC, merged