FEATURE: Send user profiles to akismet
discourse/discourse-akismet-fork pull request #37
Opened 2019-05-20 17:35 UTC by romanrizzi

2019-05-22 13:01 UTC, eviltrout requested changes
Overall excellent PR, but I would like to DRY up the reviewable-user thing.

2019-05-22 13:01 UTC, eviltrout commented on assets/javascripts/discourse/templates/components/reviewable-akismet-user.hbs
> +<div class='reviewable-user-info'>
This file seems to repeat a lot from `reviewable-user.hbs` in core. I suggest making a component to DRY that up.

2019-05-23 21:40 UTC, romanrizzi commented on assets/javascripts/discourse/templates/components/reviewable-akismet-user.hbs
> +<div class='reviewable-user-info'>
Can we extract repeated code to a component in core but don't change this one until a new beta gets released? Otherwise, we'll depend on changes that are not available in beta yet.

2019-05-24 16:36 UTC, eviltrout commented on assets/javascripts/discourse/templates/components/reviewable-akismet-user.hbs
> +<div class='reviewable-user-info'>
What we should probably do here is make this a site setting and only check profiles if it's set. Default it to off at first while we debug, then users who upgrade will not need to worry about it.

Also it's a good idea to have a setting for a feature like this anyway!

2019-05-30 18:47 UTC, romanrizzi commented on assets/javascripts/discourse/templates/components/reviewable-akismet-user.hbs
> +<div class='reviewable-user-info'>
I added the site setting and used a new component defined [here](https://github.com/discourse/discourse/pull/7655)

2019-05-30 18:53 UTC, eviltrout approved these changes

2019-05-30 19:17 UTC, merged