FIX: body[:comment_content] can be nil and strip can't be used
discourse/discourse-akismet-fork pull request #41
Opened 2019-07-26 09:28 UTC by jjaffeux

2019-07-26 14:26 UTC, eviltrout commented on lib/akismet.rb
> +      body[:comment_content] = comment_content.strip[0..31999]
It's insignificant really but you could do this: `body[:comment_content] = (body[:comment_content] || "").strip[0..31999]`

2019-07-26 14:26 UTC, eviltrout approved these changes

2019-07-28 14:14 UTC, romanrizzi requested changes
Sorry for not jumping in earlier. 

As we discussed on chat, this will send Akismet an empty body. We should add a `nil` check here:

https://github.com/discourse/discourse-akismet/blob/master/lib/discourse_akismet/users_bouncer.rb#L16

2019-07-29 14:34 UTC, closed without merging

2019-07-29 14:34 UTC, eviltrout commented
I'll close this as the wrong approach then. @romanrizzi can you handle the nil check as a follow up PR?

2019-07-29 16:02 UTC, ZogStriP commented
Fixed in https://github.com/discourse/discourse-akismet/commit/1e7d31eb76f5fde46cefc06ce54026911c769e2f.